### ISSUE TITLE
Add section for macOS

### ISSUE THREAD

**Issue by battlemidget** [canonical-web-and-design/conjure-up.io#13]
Is it possible to add a section on the main page with macOS install instructions?

Basically just

```
brew install conjure-up
```

**Comment by kwm14** [comment]
macOS section has been added to the site under 'Install conjure-up' instructions.

<img width="1440" alt="Screenshot 2019-05-13 at 15 47 21" src="https://user-images.githubusercontent.com/17748020/57631011-96f9ac80-7596-11e9-9085-77b1f2378048.png">
