### ISSUE TITLE
“00-pre-deploy” and “00-deploy-done” navigation links don’t work

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/conjure-up.io#36]
1\. Go to [any page on docs.conjure-up.io](https://docs.conjure-up.io/2.4.0/en/).
2\. If it isn’t already expanded, expand “Developer manual” in the sidebar.
3\. Expand “Steps”.
4\. Click “00-pre-deploy” or “00-deploy-done”.

What happens: Nothing.

What should happen: either
- these items are not present in the sidebar, or
- they link to the right place.

This is because the links are to anchors [`#00-pre-deploy`](https://docs.conjure-up.io/2.4.0/en/dev-manual#00-pre-deploy) and [`#00-deploy-done`](https://docs.conjure-up.io/2.4.0/en/dev-manual#00-deploy-done), which don’t exist. The real anchors are [`#00_pre-deploy`](https://docs.conjure-up.io/2.4.0/en/dev-manual#00_pre-deploy) and [`#00_deploy-done`](https://docs.conjure-up.io/2.4.0/en/dev-manual#00_deploy-done), with underscores after the numbers.

**Comment by pmahnke** [comment]
need to update https://github.com/canonical-web-and-design/docs.conjure-up.io/blob/master/en/metadata.yaml
