### ISSUE TITLE
Install instructions single out “Ubuntu Xenial 16.04”

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/conjure-up.io#37]
1\. Find [the Conjure-up install instructions](https://docs.conjure-up.io/2.4.0/en/).

What you see:
- “`conjure-up` is available on Ubuntu Xenial 16.04 LTS and macOS”

What’s wrong with this:
- It’s technically true, but misleading. Since it’s a snap, conjure-up is also available for Ubuntu 14.04, 17.04, 17.10, and 18.04. (Whether it actually _works_ on 14.04, I don’t know.)
- “Ubuntu Xenial 16.04 LTS” is unusual. Usual would be “Ubuntu 16.04 LTS”.
- There’s no full stop at the end of the sentence.

It may save time to fix #23 at the same time as this issue.

**Comment by battlemidget** [comment]
Thanks, I'm working on docs this week as well, ill tackle your other bugs too. Appreciate the feedback

**Comment by pmahnke** [comment]
adam is fixing, so closing
