### ISSUE TITLE
Styling bugs on global nav at mobile

### ISSUE THREAD

**Issue by deadlight** [canonical-web-and-design/conjure-up.io#63]
## Summary

The global nav chevrons are broken on smaller viewports

![image](https://user-images.githubusercontent.com/118614/72140679-2c00af80-3389-11ea-9395-86d40b9461d4.png)

## Process

View the site in a mobile-sized viewport and open the global nav at the bottom of the page

**Comment by sowasred2012** [comment]
Closing as this was [fixed in global-nav](https://github.com/canonical-web-and-design/global-nav/commit/6d6ca44a29e245e6a6110c69e230c70b3d2d9243#diff-ab87f433138bdba8d1b47d9ac6a8b2d2), just needed to deploy the site to prod.
